Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,31 +8,36 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
+
     - name: set up JDK 17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: gradle
+
     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@v4
       with:
         gradle-version: '8.2'
-        
+
     - name: Prepare Logo
       run: |
         mkdir -p app/src/main/res/drawable
-        cp logo.png app/src/main/res/drawable/logo.png
-        
+        cp logo.png app/src/main/res/drawable/logo.png || echo "Logo not found"
+
     - name: Build with Gradle
       env:
         GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
       run: gradle assembleDebug
 
     - name: Rename APK
-      # This command (mv) moves/renames the file before we upload it
-      run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/NotifyLog.apk
-      
+      run: |
+        # Find the APK file
+        APK_FILE=$(find app/build/outputs -name "*.apk" | head -n 1)
+        mkdir -p app/build/outputs/apk/debug
+        mv "$APK_FILE" app/build/outputs/apk/debug/NotifyLog.apk
+
     - name: Upload APK
       uses: actions/upload-artifact@v4
       with:
